version: '3.1'
services:

  demo_pg:
    image: "postgres:12"
    ports:
      - "5500:5432"
    environment:
      - POSTGRES_DB=demo_pg
      - POSTGRES_PASSWORD=PG+change_password
      - POSTGRES_USER=postgres
    networks:
      - demo-network
    volumes:
    - demo_pg:/usr/local/pgsql/data
  demo_api:
    build: .
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app_dir
      - PYTHONUNBUFFERED=1
      - SERVER_NAME=postgres
      - SERVER_HOST=http://iamrehket.localhost/api/
      - BACKEND_CORS_ORIGINS="http://nginx, http://localhost:4200, http://localhost:3000, http://localhost:8000"
      - PROJECT_NAME=DemoAPI
      - POSTGRES_SERVER=demo_pg
      - POSTGRES_DB=demo_pg
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=PG+change_password
      - POSTGRES_USER=postgres
      - POSTGRES_SCHEMA=demo
      - SECRET_KEY=p(5ca64tc#di)r9(5*__My_SECRET__!47dvg-q9=1k!wzi387
      - DEBUG_MODE=True
      - LOCAL_DEV=True
      - FIRST_SUPERUSER=user@demo.com
      - FIRST_SUPERUSER_PASSWORD=44d339666
      - USERS_OPEN_REGISTRATION=False
    depends_on:
      - demo_pg
    networks:
      - demo-network

  demo_nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - ./nginx/certs/localhost.key:/etc/ssl/private/localhost.key
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    networks:
      - demo-network
    depends_on:
      - demo_pg
      - demo_api

networks:
  demo-network:

volumes:
  demo_pg: