$env:PYTHONUNBUFFERED="1"
$env:PYTHONPATH=$PSScriptRoot # Used to tell python where stuff is.
$env:SERVER_NAME="localhost"
$env:SERVER_HOST="localhost"
$env:BACKEND_CORS_ORIGINS="http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8000"
$env:PROJECT_NAME="DemoAPI"
$env:POSTGRES_SERVER="localhost"
$env:POSTGRES_DB="demo_pg"
$env:POSTGRES_PORT="5500"
$env:POSTGRES_PASSWORD="PG+change_password"
$env:POSTGRES_USER="postgres"
$env:POSTGRES_SCHEMA="demo"
$env:SECRET_KEY="p(5ca64tc#di)r9(5*__My_SECRET__!47dvg-q9=1k!wzi387"
$env:DEBUG_MODE="True"
$env:LOCAL_DEV="True"
$env:FIRST_SUPERUSER="user@demo.com"
$env:FIRST_SUPERUSER_PASSWORD="44d339666"
$env:USERS_OPEN_REGISTRATION="False"

